In [1]:
import numpy as np

In [2]:
# Create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr2, type(arr2), arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'Prime'] <class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [3]:
arr1 = np.zeros((2, 3), dtype="int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5,), dtype="int64") #prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) # prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3) # identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) # range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3)
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [4]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape)  # dimenstions = m x n
print(arr.size) # total elements = 9
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [5]:
# Operations on arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()  #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [6]:
# Boolean Indexing

arr = np.array([1, 2, 3, 4, 5])

print(arr [arr > 2])
print(arr [arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [7]:
# Slicing

arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [8]:
# # Copy vs View
# nums = [1, 2, 3, 4, 5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [9]:
# Data Types

# arr1 = np.array([3 + 5j])
# arr2 = np.array([2 + 3j])

# print(arr1 + arr2)
# print(arr1 - arr2)

arr = np.array(["Prime", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

['Prime' {1, 2, 3} 3.14] object


In [10]:
# Multi-dimensional arrays

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_raws = np.sum(arr2D, axis = 1)
print(sum_of_raws)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [11]:
# 3D array

arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])   #2 x 3 x 2

print(arr3D, arr3D.shape)

# Indexing
print(arr3D[0, 1, 1])

# Slicing
arr3D[:, 0, :] = 99   # first row from both layers
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [12]:
# Vectorization

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr + arr2)

[ 7  9 11 13 15]


In [13]:
# Broadcasting

arr = np.array([1, 2, 3, 4, 5] )
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(arr.shape)
print(arr2.shape)

print(arr + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [20]:
# normalize

arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_array = (arr - mean)/std_dev
print(normalized_array)

print(mean)
print(std_dev)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


In [33]:
# Mathematical fnx

# aggregation

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [37]:
# power fnx

arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [42]:
# log

arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [54]:
# rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.94))
print(np.trunc(3.14))

arr = np.array([1, 2, -8, 3, 4, -5, 2, -5])

print(np.unique(arr))
print(np.sort(arr))

print(np.abs(arr))


3.0
4.0
3.0
3.0
[-8 -5  1  2  3  4]
[-8 -5 -5  1  2  2  3  4]
[1 2 8 3 4 5 2 5]
